### ISSUE TITLE
大佬，又要打扰了

### ISSUE THREAD

**Issue by Sarste** [oliverkirk-sudo/chat_voice#15]
我理解的是缺少websocket，但是出去pip install了一下回来还是说没有

**Comment by Sarste** [comment]
[2023-04-03 18:48:31.583] keymgr.py (62) - [INFO] : 使用api-key:default
[2023-04-03 18:48:31.585] manager.py (30) - [INFO] : 文字总使用量：3287
[2023-04-03 18:48:31.586] session.py (67) - [INFO] : 加载session: person_705483554
[2023-04-03 18:48:31.588] manager.py (87) - [INFO] : 加载禁用列表: person: [2854196310], group: [204785790, 691226829]
[2023-04-03 18:48:31.588] host.py (89) - [INFO] : 加载插件
[2023-04-03 18:48:31.598] mapper.py (8) - [ERROR] : 包加载错误
Traceback (most recent call last):
  File "E:\QQchat\QChatGPT\.\plugins\chat_voice\config\mapper.py", line 4, in <module>
    from plugins.chat_voice.pkg.huggingface.huggingface_session_hash import get_audio_wav
  File "E:\QQchat\QChatGPT\.\plugins\chat_voice\pkg\huggingface\huggingface_session_hash.py", line 6, in <module>
    import websocket
ModuleNotFoundError: No module named 'websocket'
[2023-04-03 18:48:31.603] mapper.py (13) - [ERROR] : 请正确配置voice_config.py
Traceback (most recent call last):
  File "E:\QQchat\QChatGPT\.\plugins\chat_voice\config\mapper.py", line 11, in <module>
    from plugins.chat_voice.config.voice_config import voice_config
  File "E:\QQchat\QChatGPT\.\plugins\chat_voice\config\voice_config.py", line 5
    "proxy_host": "127.0.0.1", #代理ip
                ^
SyntaxError: invalid syntax
[2023-04-03 18:48:31.607] host.py (83) - [ERROR] : 加载模块: plugins/chat_voice/main.py 失败: (<class 'NameError'>, NameError("name 'save_azure_wav' is not defined"), <traceback object at 0x000002372F704EC0>)
Traceback (most recent call last):
  File "E:\QQchat\QChatGPT\.\pkg\plugin\host.py", line 80, in walk_plugin_path
    importlib.import_module(module.__name__ + '.' + item.name)
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\QQchat\QChatGPT\.\plugins\chat_voice\main.py", line 6, in <module>
    from plugins.chat_voice.config.mapper import voice_type_mapping,method_mapping
  File "E:\QQchat\QChatGPT\.\plugins\chat_voice\config\mapper.py", line 21, in <module>
    'azure': save_azure_wav,
NameError: name 'save_azure_wav' is not defined
[2023-04-03 18:48:31.619] host.py (106) - [INFO] : 初始化插件
2023-04-03 18:48:31 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-04-03 18:48:31.621] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
仅 HTTP 轮询与正向 WebSocket 可用。
建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
在命令行键入：
    pip install uvicorn
或者
    pip install hypercorn
[2023-04-03 18:48:33.621] main.py (287) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
2023-04-03 18:48:33 - INFO     [WebSocket] 成功登录到账号3497910072。
[2023-04-03 18:48:33.745] websocket.py (194) - [INFO] : [WebSocket] 成功登录到账号3497910072。
2023-04-03 18:48:33 - INFO     [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
[2023-04-03 18:48:33.746] websocket.py (250) - [INFO] : [WebSocket] 机器人开始运行。按 Ctrl + C 停止。

**Comment by Sarste** [comment]
![image](https://user-images.githubusercontent.com/54228983/229489330-46eaad83-d885-41e2-945e-5eb6b0b5ae5f.png)
bug部分如上
之前还有一次，因为只用haggingface，我把vits和azure相关的代码和文件全部删掉了，当时提示找不到module av和pilk，感觉是一回事？
脑子快烧坏了

**Comment by Sarste** [comment]
![image](https://user-images.githubusercontent.com/54228983/229493944-87af79f5-d9b6-4963-aeb0-2d215c52fb22.png)
我意识到是我想错了，最开始的错误应该是最下面的吧，之前是azure没有define，把那一行#掉之后就轮到下一行hg来error了，但是在code页面搜azure甚至没搜到这一行代码，仍然力有不逮

**Comment by oliverkirk-sudo** [comment]
而且要卸载掉websocket包，因为websocket和websocket-client会冲突

**Comment by oliverkirk-sudo** [comment]
建议删除了重装一遍

**Comment by JoyousTime** [comment]
我遇到了同样的问题，大佬能详细解释一下解决方法吗

**Comment by DefensiveSniper** [comment]
同样的问题，不过解决了。应该是源文件voice_config_temp.py中第四行的"voice_type": "azure"后面没加半角逗号，所以出现
File "E:\QQchat\QChatGPT.\plugins\chat_voice\config\voice_config.py", line 5
"proxy_host": "127.0.0.1", #代理ip
^
SyntaxError: invalid syntax
加上半角逗号可以解决
