### ISSUE TITLE
[ERROR] : 插件chat_voice触发事件normal_message_responded时发生错误

### ISSUE THREAD

**Issue by niliovo** [oliverkirk-sudo/chat_voice#2]
[2023-03-17 04:09:18.838] host.py (314) - [ERROR] : 插件chat_voice触发事件normal_message_responded时发生错误
[2023-03-17 04:09:18.842] host.py (315) - [ERROR] : Traceback (most recent call last):
  File "/bot/pkg/plugin/host.py", line 308, in emit
    hook(plugin['instance'], **kwargs)
  File "/bot/plugins/chat_voice/main.py", line 76, in person_normal_message_received
    send_msg(kwargs, msg)
  File "/bot/plugins/chat_voice/main.py", line 56, in send_msg
    host.send_person_message(kwargs['launcher_id'], msg) if kwargs[
  File "/bot/pkg/plugin/host.py", line 265, in send_person_message
    asyncio.run(self.get_bot().send_friend_message(person, message))
  File "/usr/local/lib/python3.9/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 430, in __call__
    return await self.set(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 398, in set
    return await self._call_api(
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 386, in _call_api
    return await api.call(self.api_provider, method, response_type)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 318, in call
    raw_response = await self._call(api_provider, method)
  File "/usr/local/lib/python3.9/site-packages/mirai/models/api.py", line 304, in _call
    return await api_provider.call_api(
  File "/usr/local/lib/python3.9/site-packages/mirai/bot.py", line 320, in call_api
    return await self._adapter.call_api(api, *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 236, in call_api
    return await self._recv(sync_id)
  File "/usr/local/lib/python3.9/site-packages/mirai/adapters/websocket.py", line 165, in _recv
    raise exceptions.ApiError(data)
mirai.exceptions.ApiError: (6, '[ERROR 6]指定文件不存在。', '文件不存在：/bot/voice_tmp/voice_9a450129a.silk')

**Comment by oliverkirk-sudo** [comment]
请检查有没有安装FFmpeg

**Comment by oliverkirk-sudo** [comment]
有更详细的debug级别的信息嘛，我这边的ffmpeg的版本是6.0，而且不是用pip安装的，你用的这个库是二次封装的ffmpeg，不知道会不会有影响

**Comment by niliovo** [comment]
> 有更详细的debug级别的信息嘛，我这边的ffmpeg的版本是6.0，而且不是用pip安装的，你用的这个库是二次封装的ffmpeg，不知道会不会有影响

感谢回复，现在已经解决了，原因很简单，mirai无法访问到voice_tmp文件夹

**Comment by kiropoi** [comment]
> > 有更详细的debug级别的信息嘛，我这边的ffmpeg的版本是6.0，而且不是用pip安装的，你用的这个库是二次封装的ffmpeg，不知道会不会有影响
> 
> 感谢回复，现在已经解决了，原因很简单，mirai无法访问到voice_tmp文件夹

请问这个怎么解决
