### ISSUE TITLE
安装依赖报错

### ISSUE THREAD

**Issue by youyi0218** [oliverkirk-sudo/chat_voice#23]
安装依赖的时候报错
 Downloading azure_cognitiveservices_speech-1.26.0-py3-none-win_amd64.whl (1.5 MB)
     ---------------------------------------- 1.5/1.5 MB 341.5 kB/s eta 0:00:00
Collecting websocket-client~=1.5.1 (from -r requirements.txt (line 2))
  Downloading websocket_client-1.5.3-py3-none-any.whl.metadata (7.6 kB)
Collecting av~=10.0.0 (from -r requirements.txt (line 3))
  Downloading av-10.0.0-cp310-cp310-win_amd64.whl (25.3 MB)
     ---------------------------------------- 25.3/25.3 MB 11.3 MB/s eta 0:00:00
Collecting pilk~=0.2.3 (from -r requirements.txt (line 4))
  Downloading pilk-0.2.4-cp310-cp310-win_amd64.whl.metadata (8.9 kB)
Collecting pyopenjtalk~=0.3.0 (from -r requirements.txt (line 5))
  Downloading pyopenjtalk-0.3.3.tar.gz (1.6 MB)
     ---------------------------------------- 1.6/1.6 MB 11.1 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      CMake Error at CMakeLists.txt:17 (project):
        Running

         'nmake' '-?'

        failed with:

         no such file or directory

      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      CMake is in the system path. Version:               cmake version 3.28.1

      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      Traceback (most recent call last):
        File "D:\python\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\python\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\python\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\youyi\AppData\Local\Temp\pip-build-env-mv9ct564\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\youyi\AppData\Local\Temp\pip-build-env-mv9ct564\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\youyi\AppData\Local\Temp\pip-build-env-mv9ct564\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 191, in <module>
        File "D:\python\3.10.11\lib\subprocess.py", line 457, in check_returncode
          raise CalledProcessError(self.returncode, self.args, self.stdout,
      subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

D:\Program\QChatGPT\plugins\chat_voice>pip install -r requirements.txt
Collecting azure-cognitiveservices-speech~=1.26.0 (from -r requirements.txt (line 1))
  Using cached azure_cognitiveservices_speech-1.26.0-py3-none-win_amd64.whl (1.5 MB)
Collecting websocket-client~=1.5.1 (from -r requirements.txt (line 2))
  Using cached websocket_client-1.5.3-py3-none-any.whl.metadata (7.6 kB)
Collecting av~=10.0.0 (from -r requirements.txt (line 3))
  Using cached av-10.0.0-cp310-cp310-win_amd64.whl (25.3 MB)
Collecting pilk~=0.2.3 (from -r requirements.txt (line 4))
  Using cached pilk-0.2.4-cp310-cp310-win_amd64.whl.metadata (8.9 kB)
Collecting pyopenjtalk~=0.3.0 (from -r requirements.txt (line 5))
  Using cached pyopenjtalk-0.3.3.tar.gz (1.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      CMake Error at CMakeLists.txt:17 (project):
        Running

         'nmake' '-?'

        failed with:

         no such file or directory

      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      CMake is in the system path. Version:               cmake version 3.28.1

      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      Traceback (most recent call last):
        File "D:\python\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\python\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\python\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\youyi\AppData\Local\Temp\pip-build-env-edv5fsox\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\youyi\AppData\Local\Temp\pip-build-env-edv5fsox\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\youyi\AppData\Local\Temp\pip-build-env-edv5fsox\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 191, in <module>
        File "D:\python\3.10.11\lib\subprocess.py", line 457, in check_returncode
          raise CalledProcessError(self.returncode, self.args, self.stdout,
      subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

D:\Program\QChatGPT\plugins\chat_voice>pip install -r requirements.txt
Collecting azure-cognitiveservices-speech~=1.26.0 (from -r requirements.txt (line 1))
  Using cached azure_cognitiveservices_speech-1.26.0-py3-none-win_amd64.whl (1.5 MB)
Collecting websocket-client~=1.5.1 (from -r requirements.txt (line 2))
  Using cached websocket_client-1.5.3-py3-none-any.whl.metadata (7.6 kB)
Collecting av~=10.0.0 (from -r requirements.txt (line 3))
  Using cached av-10.0.0-cp310-cp310-win_amd64.whl (25.3 MB)
Collecting pilk~=0.2.3 (from -r requirements.txt (line 4))
  Using cached pilk-0.2.4-cp310-cp310-win_amd64.whl.metadata (8.9 kB)
Collecting pyopenjtalk~=0.3.0 (from -r requirements.txt (line 5))
  Using cached pyopenjtalk-0.3.3.tar.gz (1.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [44 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      -- Building for: NMake Makefiles
      CMake Deprecation Warning at CMakeLists.txt:5 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.

        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.

      CMake Error at CMakeLists.txt:17 (project):
        Running

         'nmake' '-?'

        failed with:

         no such file or directory

      CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
      CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
      -- Configuring incomplete, errors occurred!
      CMake is in the system path. Version:               cmake version 3.28.1

      CMake suite maintained and supported by Kitware (kitware.com/cmake).
      Traceback (most recent call last):
        File "D:\python\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\python\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\python\3.10.11\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\youyi\AppData\Local\Temp\pip-build-env-l0_5unzm\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\youyi\AppData\Local\Temp\pip-build-env-l0_5unzm\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\youyi\AppData\Local\Temp\pip-build-env-l0_5unzm\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 191, in <module>
        File "D:\python\3.10.11\lib\subprocess.py", line 457, in check_returncode
          raise CalledProcessError(self.returncode, self.args, self.stdout,
      subprocess.CalledProcessError: Command '['cmake', '..', '-DHTS_ENGINE_INCLUDE_DIR=.', '-DHTS_ENGINE_LIB=dummy']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by youyi0218** [comment]
自己摸索了半天终于好了希望作者能把更详细的步骤写入readme
首先是要下载cmake，然后下载visual studio，并在里面下载c++相关组件（他推荐的，然后我是win10就多勾了一个win10sdk）然后重新安装就好了
